"""
pg_schema.py — the PostgreSQL schema, mirroring the SQLite schema exactly.

This is a 1:1 translation of what ``database.py`` creates on SQLite (plus the
additive migrations it applies), so PostgreSQL becomes a drop-in replacement
rather than "a new unrelated schema":

    SQLite                                   PostgreSQL
    ---------------------------------------  ---------------------------------
    INTEGER PRIMARY KEY AUTOINCREMENT        SERIAL PRIMARY KEY
    TEXT                                     TEXT
    INTEGER (0/1 flags)                      INTEGER        (deliberately kept)
    REAL                                     DOUBLE PRECISION
    TIMESTAMP DEFAULT CURRENT_TIMESTAMP      TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
    REFERENCES users(id)                     REFERENCES users(id)  (now enforced)
    CREATE INDEX IF NOT EXISTS ...           CREATE INDEX IF NOT EXISTS ...

Two deliberate decisions, both taken to avoid changing behaviour the frontend
can see:

* **The 0/1 flags stay INTEGER.** ``is_verified``, ``interview_blocked`` and
  ``cheat_strikes`` are integers in SQLite, so the API keeps returning ``1``/``0``
  and the admin UI keeps working untouched. Converting them to ``boolean`` would
  silently change the JSON contract.
* **Timestamps stay naive UTC.** SQLite stored ``'YYYY-MM-DD HH:MM:SS'`` in UTC
  with no timezone. PostgreSQL's ``now() AT TIME ZONE 'utc'`` reproduces that
  exactly, so date arithmetic in the admin dashboard means the same thing.

The one intentional semantic difference is documented in the migration report:
PostgreSQL **enforces** foreign keys, where SQLite had them declared but off.
"""

from __future__ import annotations

# Tables in dependency order (parents first) — used by the migration script and
# by the test harness when it needs to clear state.
TABLES_IN_ORDER = [
    "users",
    "questions",
    "interviews",
    "answers",
    "activity_logs",
    "feedback",
]

SCHEMA_SQL: list[str] = [
    # ── users ──────────────────────────────────────────────────────────────
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        email TEXT UNIQUE,
        password_hash TEXT,
        google_id TEXT,
        avatar_url TEXT,
        target_role TEXT DEFAULT 'Software Engineer',
        is_verified INTEGER DEFAULT 0,
        verification_token TEXT,
        verification_token_expires TEXT,
        created_at TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
        reset_token TEXT,
        reset_token_expires TEXT,
        role TEXT DEFAULT 'user',
        last_login TIMESTAMP,
        cheat_strikes INTEGER DEFAULT 0,
        interview_blocked INTEGER DEFAULT 0
    )
    """,
    # ── questions ──────────────────────────────────────────────────────────
    """
    CREATE TABLE IF NOT EXISTS questions (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        role TEXT NOT NULL,
        category TEXT CHECK(category IN ('Behavioral', 'Technical', 'Situational')) NOT NULL,
        question_text TEXT NOT NULL,
        optimal_keywords TEXT,
        expected_concepts TEXT,
        difficulty TEXT CHECK(difficulty IN ('Easy', 'Medium', 'Hard')) NOT NULL
    )
    """,
    # ── interviews ─────────────────────────────────────────────────────────
    """
    CREATE TABLE IF NOT EXISTS interviews (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id INTEGER,
        role TEXT NOT NULL,
        date TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
        overall_score DOUBLE PRECISION,
        summary TEXT
    )
    """,
    # ── answers ────────────────────────────────────────────────────────────
    """
    CREATE TABLE IF NOT EXISTS answers (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        interview_id INTEGER,
        question_id INTEGER,
        transcript TEXT,
        feedback_json TEXT,
        score DOUBLE PRECISION
    )
    """,
    # ── activity_logs ──────────────────────────────────────────────────────
    """
    CREATE TABLE IF NOT EXISTS activity_logs (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id INTEGER,
        activity_type TEXT NOT NULL,
        description TEXT,
        status TEXT DEFAULT 'success',
        ip_address TEXT,
        user_agent TEXT,
        details TEXT,
        created_at TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
    )
    """,
    # ── feedback ───────────────────────────────────────────────────────────
    """
    CREATE TABLE IF NOT EXISTS feedback (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_email TEXT,
        interview_rating INTEGER,
        website_rating INTEGER,
        comment TEXT,
        created_at TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
    )
    """,
    # ── SQLite-compatible numeric rounding ─────────────────────────────────
    # SQLite's ROUND(float, digits) works on a REAL; PostgreSQL only defines
    # round(numeric, int). The admin dashboard calls ROUND(AVG(score), 1), so the
    # two-argument overload is provided here and that query stays untouched.
    """
    CREATE OR REPLACE FUNCTION round(double precision, integer)
    RETURNS double precision
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    AS $$ SELECT round($1::numeric, $2)::double precision $$
    """,
    # ── indexes (same three SQLite created) ────────────────────────────────
    "CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON activity_logs(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_activity_logs_type ON activity_logs(activity_type)",
    "CREATE INDEX IF NOT EXISTS idx_activity_logs_created ON activity_logs(created_at DESC)",
]


# The relationships the SQLite schema declared. They are added with NOT VALID and
# then validated separately (see validate_constraints): a NOT VALID constraint is
# still enforced for every new INSERT and UPDATE, but it tolerates rows that
# already violate it. That matters because the legacy SQLite database contains a
# few orphaned rows (SQLite never enforced these), and the migration has to carry
# those rows over untouched instead of deleting or rewriting them.
FK_DEFINITIONS = [
    # (constraint name, table, column, referenced table, referenced column, ON DELETE)
    ("interviews_user_id_fkey", "interviews", "user_id", "users", "id", "CASCADE"),
    ("answers_interview_id_fkey", "answers", "interview_id", "interviews", "id", "CASCADE"),
    ("activity_logs_user_id_fkey", "activity_logs", "user_id", "users", "id", "CASCADE"),
]

# Relationships that are declared in the SQLite schema but deliberately NOT
# enforced here, because enforcing them would break a working feature:
#
#   answers.question_id -> questions.id
#
# `/api/questions` falls back to AI-generated questions when the bank has none
# for a role, and those questions are never written to the questions table —
# their ids (-1, -2, ...) are session-local. The interview room submits answers
# for them, so every such submission would fail with a foreign-key violation.
# SQLite declared this reference but never enforced it, and the legacy database
# already contains rows that violate it, so the column and its index are kept
# while enforcement is not. (To tighten this later, persist AI questions in the
# bank first, then re-add the constraint.)
FK_UNENFORCED = [
    ("answers_question_id_fkey", "answers", "question_id", "questions", "id"),
]


def _constraint_exists(cursor, name: str) -> bool:
    cursor.execute(
        "SELECT 1 FROM pg_constraint "
        "WHERE conname = %s AND connamespace = current_schema()::regnamespace",
        (name,),
    )
    return cursor.fetchone() is not None


def create_schema(conn, with_foreign_keys: bool = True) -> None:
    """Create every table, index and (optionally) foreign key that is missing.

    Safe to run repeatedly, and safe to run against a database that already
    holds rows. The migration passes ``with_foreign_keys=False`` so legacy rows
    can be loaded first, then calls ``add_foreign_keys`` afterwards.
    """
    cursor = conn.raw_cursor() if hasattr(conn, "raw_cursor") else conn.cursor()
    try:
        for statement in SCHEMA_SQL:
            cursor.execute(statement)
        if with_foreign_keys:
            for name, table, column, ref_table, ref_column, on_delete in FK_DEFINITIONS:
                if _constraint_exists(cursor, name):
                    continue
                cursor.execute(
                    f"ALTER TABLE {table} ADD CONSTRAINT {name} FOREIGN KEY ({column}) "
                    f"REFERENCES {ref_table}({ref_column}) ON DELETE {on_delete} NOT VALID"
                )
    finally:
        cursor.close()
    conn.commit()


def add_foreign_keys(conn) -> list[str]:
    """Add any missing relationship as NOT VALID. Returns the names added."""
    added: list[str] = []
    cursor = conn.raw_cursor()
    try:
        for name, table, column, ref_table, ref_column, on_delete in FK_DEFINITIONS:
            if _constraint_exists(cursor, name):
                continue
            cursor.execute(
                f"ALTER TABLE {table} ADD CONSTRAINT {name} FOREIGN KEY ({column}) "
                f"REFERENCES {ref_table}({ref_column}) ON DELETE {on_delete} NOT VALID"
            )
            added.append(name)
    finally:
        cursor.close()
    conn.commit()
    return added


def drop_foreign_keys(conn, names) -> list[str]:
    """Remove the named relationships so legacy rows can be loaded.

    Only ever called by the migrator, which re-adds them in the same run (see
    add_foreign_keys) — a NOT VALID constraint still rejects new orphan rows,
    so it has to be absent while the legacy rows are inserted.
    """
    dropped: list[str] = []
    cursor = conn.raw_cursor()
    try:
        for name, table, _column, _ref_table, _ref_column, _on_delete in FK_DEFINITIONS:
            if name not in names:
                continue
            if not _constraint_exists(cursor, name):
                continue
            cursor.execute(f"ALTER TABLE {table} DROP CONSTRAINT {name}")
            dropped.append(name)
    finally:
        cursor.close()
    conn.commit()
    return dropped


def count_orphans(conn) -> dict[str, int]:
    """Rows per relationship that reference a row which does not exist.

    Covers the enforced relationships and the documented unenforced one, so the
    migration report can state exactly how much legacy dangling data exists.
    """
    counts: dict[str, int] = {}
    cursor = conn.raw_cursor()
    try:
        pairs = [(n, t, c, r, rc) for n, t, c, r, rc, _d in FK_DEFINITIONS]
        pairs += list(FK_UNENFORCED)
        for name, table, column, ref_table, ref_column in pairs:
            cursor.execute(
                f"SELECT COUNT(*) FROM {table} child "
                f"WHERE child.{column} IS NOT NULL AND NOT EXISTS ("
                f"  SELECT 1 FROM {ref_table} parent WHERE parent.{ref_column} = child.{column})"
            )
            counts[name] = int(cursor.fetchone()[0])
    finally:
        cursor.close()
    return counts


def validate_constraints(conn) -> dict[str, str]:
    """Try to promote each foreign key from NOT VALID to fully validated.

    Returns ``{constraint: status}``. A constraint whose table still holds
    orphaned rows stays NOT VALID — the data is preserved, new writes are still
    checked, and the caller can report exactly which rows need attention.
    """
    status: dict[str, str] = {}
    for name, table, _column, _ref_table, _ref_column, _on_delete in FK_DEFINITIONS:
        cursor = conn.raw_cursor()
        try:
            cursor.execute(f"ALTER TABLE {table} VALIDATE CONSTRAINT {name}")
            conn.commit()
            status[name] = "validated"
        except Exception as exc:  # noqa: BLE001 - reported, never fatal
            conn.rollback()
            status[name] = f"NOT VALID ({type(exc).__name__})"
        finally:
            cursor.close()
    return status


def reset_sequences(conn) -> dict[str, int]:
    """Re-point every identity sequence at MAX(id) + 1.

    Required because the migration inserts rows with their original explicit
    ids; without this, the next INSERT would try to reuse id 1 and fail.
    """
    fixed: dict[str, int] = {}
    cursor = conn.raw_cursor() if hasattr(conn, "raw_cursor") else conn.cursor()
    try:
        for table in TABLES_IN_ORDER:
            cursor.execute(f"SELECT COALESCE(MAX(id), 0) FROM {table}")
            row = cursor.fetchone()
            high = int(row[0]) if row else 0
            cursor.execute(
                "SELECT setval(pg_get_serial_sequence(%s, 'id'), %s, %s)",
                (table, max(high, 1), high > 0),
            )
            fixed[table] = high
    finally:
        cursor.close()
    conn.commit()
    return fixed


def truncate_tables(conn) -> None:
    """Empty every table and restart identities (used by the PostgreSQL test mode)."""
    cursor = conn.raw_cursor() if hasattr(conn, "raw_cursor") else conn.cursor()
    try:
        cursor.execute(
            "TRUNCATE TABLE " + ", ".join(TABLES_IN_ORDER)
            + " RESTART IDENTITY CASCADE"
        )
    finally:
        cursor.close()
    conn.commit()
